version: "3.8"

services:
  dentalclinic:
    build: ./dentalclinic
    command: gunicorn dentalclinic.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
      - static_volume:/app/static
      - media_volume:/app/media
      - ./certs:/etc/letsencrypt
    networks:
      - mynetwork
    depends_on:
      - dentalclinic
    command: nginx -g 'daemon off;'
  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
    command: /bin/sh -c "init-ssl.sh"

networks:
  mynetwork:
    driver: bridge

volumes:
  static_volume:
  media_volume:
  certs: