# Generated by Django 5.0 on 2024-02-24 21:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_appointment_service_service_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='order_number',
            field=models.PositiveIntegerField(default=19812, validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(99999)], verbose_name='Номер заказа'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='order_status',
            field=models.IntegerField(choices=[(1, 'Создана'), (2, 'Принято'), (3, 'В процессе'), (4, 'Выполнен'), (5, 'Отменен')], default=1, verbose_name='Статус'),
        ),
    ]
