# Generated by Django 5.0 on 2024-02-24 21:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_appointment_order_number_appointment_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='order_number',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(99999)], verbose_name='Номер заказа'),
        ),
    ]
