# Generated by Django 5.0 on 2024-02-26 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='end_time',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AddField(
            model_name='profile',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
