# Generated by Django 5.0 on 2024-02-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_appointment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='main.service', verbose_name='Услуги'),
        ),
    ]
