# Generated by Django 5.0 on 2024-03-19 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_profile_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentservice',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_services', to='main.appointment'),
        ),
    ]
