# Generated by Django 5.0 on 2024-03-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_appointmentservice_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='user_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='user_name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='user_phone',
            field=models.CharField(default=2, max_length=25),
            preserve_default=False,
        ),
    ]
