# Generated by Django 5.0 on 2024-03-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_appointment_user_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='specialization',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='order_status',
            field=models.IntegerField(choices=[(1, 'Создан'), (2, 'Принято'), (3, 'В процессе'), (4, 'Выполнен'), (5, 'Отменен')], default=1, verbose_name='Статус'),
        ),
    ]
