# Generated by Django 5.0 on 2024-03-26 00:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_profile_specialization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='user_name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='appointment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
