# Generated by Django 5.0 on 2024-03-26 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_rename_user_name_appointment_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
